server:
  port: 8080
waliwa: B

spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.51.1:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: lhxLHX854*%$
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 80
      names: ds1,ds2
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.51.1:3306/test2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: lhxLHX854*%$
      ds2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.51.1:3306/test2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: lhxLHX854*%$