server:
  port: 80
waliwa: A


spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://172.20.20.103:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: zhubajie
      driver-class-name: com.mysql.jdbc.Driver
      maximum-pool-size: 80
      names: ds1,ds2
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.20.20.103:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: zhubajie
      ds2:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://172.20.20.103:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: zhubajie