server:
  port: 8080
waliwa: A


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.20.20.103:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zhubajie
    driver-class-name: com.mysql.jdbc.Driver
    maximum-pool-size: 80
    names: ds1,ds2
    ds1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.20.103:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: zhubajie
    ds2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.20.20.103:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: zhubajie
    # Redis配置
  redis:
    host: 192.168.51.1
    port: 6379
    password: 854854
  # 连接超时时间（毫秒）
    timeout: 20000
    pool:
      max-idle: 20
      min-idle: 1
      max-active: 20
      max-wait: -1